[env:genericSTM32F401RC]
platform        = ststm32
board           = genericSTM32F401RC
framework       = stm32cube
upload_protocol = stlink
monitor_speed   = 9600
build_flags     =
    -DSTM32F401xC
    -DUSE_FULL_LL_DRIVER
    -DHSE_VALUE=8000000
